In [1]:
# syntax:
# DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [2]:
# create dataframe from lists
import pandas as pd

# List of lists
data = [['a1', 'b1', 'c1'],
        ['a2', 'b2', 'c2'],
        ['a3', 'b3', 'c3']]

df = pd.DataFrame(data)
print(df)

    0   1   2
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3


In [3]:
# creating dataframes from Dictionaries
import pandas as pd

# List of lists
data = {'col1': ['a1', 'a2', 'a3'],
        'col2': ['b1', 'b2', 'b3'],
        'col3': ['c1', 'c2', 'c3']}

df = pd.DataFrame(data)
print(df)

  col1 col2 col3
0   a1   b1   c1
1   a2   b2   c2
2   a3   b3   c3


In [4]:
# empty dataframe 
import pandas as pd

df = pd.DataFrame(columns=['name', 'age', 'country'])
print(df)

Empty DataFrame
Columns: [name, age, country]
Index: []


In [5]:
#data frame from dictionary 
import pandas as pd

mydictionary = {'names': ['Somu', 'Kiku', 'Amol', 'Lini'],
	'physics': [68, 74, 77, 78],
	'chemistry': [84, 56, 73, 69],
	'algebra': [78, 88, 82, 87]}

# Create dataframe using dictionary
df_marks = pd.DataFrame(mydictionary)

print(df_marks)

  names  physics  chemistry  algebra
0  Somu       68         84       78
1  Kiku       74         56       88
2  Amol       77         73       82
3  Lini       78         69       87


In [6]:
#  dataframe from Numpy Array
import pandas as pd
import numpy as np

array = np.array([['a1', 'b1', 'c1'],
                  ['a2', 'b2', 'c2'],
                  ['a3', 'b3', 'c3']])
df = pd.DataFrame(array)
print(df)

    0   1   2
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3


In [ ]:
# DataFrame from Numpy Array, along with column names and index
import pandas as pd
import numpy as np

array = np.array([['a1', 'b1', 'c1'],
                  ['a2', 'b2', 'c2'],
                  ['a3', 'b3', 'c3']])

columns = ['aN', 'bN', 'cN']
index = [1, 2, 3]

df = pd.DataFrame(array, index, columns)
print(df)

In [7]:
# Inner join DataFrames along an axis
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'B': ['B2', 'B3', 'B4', 'B5'],
                    'D': ['D2', 'D3', 'D4', 'D5'],
                    'F': ['F2', 'F3', 'F4', 'F5']},
                   index=[2, 3, 4, 5])

result = pd.concat([df1, df2], axis=1, join='inner')

print(result)

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3


In [12]:
# Remove duplicate rows from DataFrame based on all columns using drop_duplicates() method
import pandas as pd

df = pd.DataFrame({
        'A': [1, 2, 1, 1, 3],
        'B': [5, 4, 5, 5, 5],
        'C': [9, 10, 9, 9, 8]})

df_no_duplicates = df.drop_duplicates()
print(f"Original DataFrame\n{df}\n")
print(f"DataFrame with no duplicates\n{df_no_duplicates}")

Original DataFrame
   A  B   C
0  1  5   9
1  2  4  10
2  1  5   9
3  1  5   9
4  3  5   8

DataFrame with no duplicates
   A  B   C
0  1  5   9
1  2  4  10
4  3  5   8


In [13]:
# Remove duplicate rows from DataFrame based on a single column using drop_duplicates() method

import pandas as pd

# Take a sample DataFrame
df = pd.DataFrame({
        'A': [1, 2, 1, 1, 3],
        'B': [5, 4, 5, 5, 5],
        'C': [9, 10, 9, 9, 8]})

# Remove duplicate rows based on column 'B'
df_no_duplicates = df.drop_duplicates(subset=['B'])

print(f"Original DataFrame\n{df}\n")
print(f"DataFrame with no duplicates\n{df_no_duplicates}")

Original DataFrame
   A  B   C
0  1  5   9
1  2  4  10
2  1  5   9
3  1  5   9
4  3  5   8

DataFrame with no duplicates
   A  B   C
0  1  5   9
1  2  4  10


In [14]:
# Remove duplicate rows from DataFrame based on multiple columns using drop_duplicates() method
import pandas as pd

# Take a sample DataFrame
df = pd.DataFrame({
        'A': [1, 2, 1, 1, 3],
        'B': [5, 4, 5, 5, 5],
        'C': [9, 10, 9, 9, 8]})

# Remove duplicate rows based on all columns
df_no_duplicates = df.drop_duplicates(subset=['A', 'B'])

print(f"Original DataFrame\n{df}\n")
print(f"DataFrame with no duplicates\n{df_no_duplicates}")

Original DataFrame
   A  B   C
0  1  5   9
1  2  4  10
2  1  5   9
3  1  5   9
4  3  5   8

DataFrame with no duplicates
   A  B   C
0  1  5   9
1  2  4  10
4  3  5   8


In [15]:
# Iterate over cells in DataFrame using DataFrame.shape and For loop
import pandas as pd
import numpy as np

df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]])

for i in range(df.shape[0]): #iterate over rows
    for j in range(df.shape[1]): #iterate over columns
        value = df.at[i, j] #get cell value
        print(value, end="\t")
    print()

1	2	3	
4	5	6	
7	8	9	
10	11	12	


In [17]:
# Iterate over Cells in a DataFrame using iterrows() method
import pandas as pd
import numpy as np

df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]])

for rowIndex, row in df.iterrows(): #iterate over rows
    for columnIndex, value in row.items():
        print(value, end="\t")
    print()
# Convert DataFrame to numpy array
arr = df.to_numpy()
print('\nNumpy Array\n----------\n', arr)  

1	2	3	
4	5	6	
7	8	9	
10	11	12	

Numpy Array
----------
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
