In [1]:
import numpy as np

# Create a simple array with integers
simple_array = np.array([1, 2, 3, 4, 5])
print(simple_array)

[1 2 3 4 5]


In [2]:
# Create a 2D array (matrix)
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_array)


[[1 2 3]
 [4 5 6]]


In [3]:
# Create an array with a range of elements
range_array = np.arange(10)
print(range_array)

# Create an array with a range of floats
float_array = np.arange(2, 10, dtype=float)
print(float_array)

# Create an array with a step size
step_array = np.arange(2, 3, 0.1)
print(step_array)


[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [4]:
# Reshape a 1D array to a 3D array
arr = np.arange(36)
reshaped_arr = arr.reshape(3, 4, 3)
print(reshaped_arr)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
